import assert from 'node:assert/strict';
import fs from 'node:fs';

const source=fs.readFileSync(new URL('../tools/pdf_review_native.mjs',import.meta.url),'utf8');
assert.match(source,/data-requirement-badge="true"/);
assert.match(source,/const visibleSvg=svg/);
assert.match(source,/data-requirement-legend="true"/);
assert.match(source,/Directly attached requirements/);
assert.match(source,/Subtype:PDFName\.of\('Text'\)/);
assert.doesNotMatch(source,/Subtype:PDFName\.of\('Link'\)/);
assert.match(source,/Contents:PDFHexString\.fromText\(reqs\.join\('\\n\\n'\)\)/);
assert.match(source,/ui/);
assert.match(source,/x\+3\*r\+12,y-r,x\+5\*r\+12,y\+r/);
assert.match(source,/\? \[x\+3\*r\+12,y-r,x\+5\*r\+12,y\+r\]/);
assert.match(source,/: \[x-10,y\+r,x\+10,y\+r\+20\]/);
assert.doesNotMatch(source,/Tillbaka till diagrammet/);
assert.match(source,/const names=\['context','pulse','ui','deployment'\]/);
assert.match(source,/path\.join\(out,`\$\{name\}\.pdf`\)/);
assert.doesNotMatch(source,/review\.pdf/);
assert.match(source,/page\.drawLine/);
assert.match(source,/page\.drawCircle/);
assert.match(source,/page\.drawRectangle/);
assert.match(source,/name==='deployment'\?\[\]:\(page\.__boxes\|\|\[\]\)/);
assert.doesNotMatch(source,/review-native\.pdf/);
console.log('Native PDF review contract checks passed');
