direction: right
"example": "Example System" {
 shape: rectangle
 style.stroke-width: 3
}
"user": "User" {
 shape: person
 
}
"user" -> "example": "User input"
"example" -> "user": "System information"