direction: right
"process-input": "Process input" {
 shape: rectangle
 style.border-radius: 12
}
"trigger_0": "User submits input" {
 shape: rectangle
 style.fill: transparent
style.stroke: transparent
}
"trigger_0" -> "process-input"