direction: right
"main": "Main" {
style.border-radius: 12
grid-columns: 2
grid-gap: 24
actions: "" {
style.stroke: transparent
style.fill: transparent
grid-columns: 1
grid-gap: 16
"submit-input": "▶ Submit input" {
 shape: rectangle
 style.stroke: transparent
style.fill: transparent
}
}
information: "" {
style.stroke: transparent
style.fill: transparent
grid-columns: 1
grid-gap: 16
"current-status": "● Current status" {
 shape: rectangle
 style.stroke: transparent
style.fill: transparent
}
}
}